name: Bug report
description: Report a reproducible bug or regression.
title: "bug: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to file a bug. Please provide as much detail as you can.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened, and what did you expect to happen?
      placeholder: A short, clear description of the bug.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Provide a minimal, reproducible set of steps.
      placeholder: |
        1. Run ...
        2. Click ...
        3. See error ...
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs / output
      description: Paste relevant logs or command output.
      render: shell
  - type: input
    id: version
    attributes:
      label: Version
      description: Output of `statespace --version` or the git SHA.
      placeholder: v0.1.0
    validations:
      required: true
  - type: input
    id: platform
    attributes:
      label: Platform
      description: OS and architecture.
      placeholder: macOS 14.3 (arm64)
    validations:
      required: true
