name: Feature request
description: Suggest a new feature or improvement.
title: "feature: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for the idea. Please include context and any constraints.
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem are you trying to solve?
      placeholder: I need to...
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: What do you want to happen?
      placeholder: I propose...
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any alternative approaches or workarounds?
      placeholder: I tried...
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Links, screenshots, or references.
